spring:
  application:
    name: shops
  data:
    mongodb:
      auto-index-creation: true
      host: localhost
      port: 27017
      database: rtu_shops
#  jpa:
#    hibernate:
#      ddl-auto: create
#    generate-ddl: true
#  datasource:
#    url: jdbc:postgresql://localhost:5432/rtu_shops
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: root
#eureka:
#  client:
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
server:
  port: 8002