spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rtu_auth
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  application:
    name: auth
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
